version: '3'
services:
  db:
    container_name: respa-db
    build: ./docker/postgres/
    restart: on-failure
    environment:
        POSTGRES_USER: respa
        POSTGRES_PASSWORD: respa
        POSTGRES_DB: respa
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    container_name: tre-respa-api
    image: tre-respa
    build:
      target: development
      context: "."
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DEV_SERVER=1
      - WAIT_FOR_DATABASE=1
      - DATABASE_URL=postgis://respa:respa@db/respa
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
    db_data:
