# Generated by Django 2.2.11 on 2021-10-26 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0091_add_two_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slot_size',
            field=models.DurationField(default=datetime.timedelta(0, 1800), verbose_name='Slot size for reservation time in calendar view'),
        ),
    ]
